spring.application.name=Todo-App

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/demo_db
spring.datasource.username=root
spring.datasource.password=Dhruvgoel@261062

# JPS/Hibernate configuration
spring.jpa.properties.hibernate,dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




